EVENT_KEYS=0  
EVENT_TOUCHED=1 
EVENT_TOUCHUP=2
EVENT_TOUCHDOWN=3 # intra keypad events

BLACK=(0,0,0)
COLOR_BLACK =(0,0,0)
COLOR_WHITE=(255,255,255)

EVENT_RFID_GETFIRMWAREVERSION   = 23

EVENT_RFID_HASTAG               = 21
EVENT_RFID_SWITCHDOWN           = 22
EVENT_RFID_SWITCHUP             = 28

EVENT_MQTTERROR = 40
EVENT_MQTTMESSAGE = 41

EVENT_BLUEDEVICE=7  # intradispatcher message;  we have seen a compatible bluetooth device

BLACK=(0,0,0)
COLOR_BLACK =(0,0,0)
COLOR_WHITE=(255,255,255)

EVENT_PINON = 31
EVENT_PINOFF = 32
EVENT_LOCKED = 33
EVENT_UNLOCKED = 34



